services:
  - type: web
    name: ai-sre-dashboard
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /api/health
    plan: free